# Generated by Django 5.2.3 on 2025-10-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(default='Founded in 2016, Mamochoko Secondary School is commited to providing quality education in the heart of Moletjie, Ga-Kobo')),
                ('about_image', models.ImageField(upload_to='about_imgs')),
                ('hero_img', models.ImageField(upload_to='heros')),
                ('mission', models.TextField(default='Motivate staff and members on a continuous basis in order to promote the spirit of learning and teaching to produce high quality education.')),
                ('vision', models.TextField(default='To equipt our learners with high quality education that will provide them with skill, knowledge and values necessary to produce marketable citizens.')),
                ('history_and_achievements', models.TextField(default='Over the past 9 years, our students have excelled in competitions, achieved top matric results, and made our community proud.')),
                ('facilities_and_programs', models.TextField(default='Our campus includes mordern sports equipment for our sports-loving students, whiteboards for flexible learning integration, sports fields (netball & soccer), and much more.')),
                ('community_and_culture', models.TextField(default='We foster a supportive and inclusive environment where students are encouraged to explore their passions and grow academically and personally. We live by our motto "Preparing Future Leaders" on a daily basis; through our teachers\' guidance and support, we shape our students into great future leaders of tomorrow.')),
            ],
        ),
        migrations.CreateModel(
            name='AboutTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='Limpopo, Polokwane, Moletjie, Ga-Kobo, Stand no. 406 PO BOX 3192, KOLOTI 0709')),
                ('email', models.EmailField(default='mamochokos@gmail.com', max_length=254)),
                ('phone', models.CharField(default='066 559 8863')),
                ('facebook', models.URLField(default='#facebook_page_link')),
                ('image', models.ImageField(upload_to='contact_imgs')),
                ('logo', models.ImageField(upload_to='logos')),
                ('visiting_hours', models.CharField(default='10:45-11:30')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField()),
                ('text', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='UniformImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uniform_imgs')),
            ],
        ),
    ]
