# Generated by Django 5.2.3 on 2025-10-19 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='reviewers')),
                ('stars', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('body', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='moments_image',
            field=models.ImageField(blank=True, null=True, upload_to='moments_imgs'),
        ),
        migrations.AddField(
            model_name='about',
            name='resources_image',
            field=models.ImageField(blank=True, null=True, upload_to='resources_imgs'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_imgs'),
        ),
        migrations.AlterField(
            model_name='about',
            name='hero_img',
            field=models.ImageField(blank=True, null=True, upload_to='heros'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_imgs'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='uniformimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uniform_imgs'),
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
