# Generated by Django 5.2.3 on 2025-10-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_info', '0002_review_about_moments_image_about_resources_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='UserAction',
        ),
    ]
