# Generated by Django 5.2.3 on 2025-10-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_info', '0003_delete_review_delete_useraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='community_and_culture',
        ),
        migrations.RemoveField(
            model_name='about',
            name='facilities_and_programs',
        ),
        migrations.RemoveField(
            model_name='about',
            name='history_and_achievements',
        ),
        migrations.AddField(
            model_name='uniformimage',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schooltime',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
