# Generated by Django 5.2.3 on 2025-10-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_info', '0004_remove_about_community_and_culture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooltime',
            options={'ordering': ['time']},
        ),
    ]
