# Generated by Django 5.2 on 2025-04-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('wrote', models.IntegerField()),
                ('passed', models.IntegerField()),
                ('pass_rate', models.FloatField()),
                ('position', models.IntegerField()),
            ],
        ),
    ]
