# Generated by Django 5.2.3 on 2025-10-19 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(default="One of Mamochoko's moments")),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='moments')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='reviewers')),
                ('stars', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('body', models.TextField(max_length=100)),
                ('pending', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('grade_applied_for', models.IntegerField(default=8)),
                ('highest_grade_passed', models.IntegerField(default=7)),
                ('year_when_grade_was_passed', models.IntegerField(default=2025)),
                ('learner_surname', models.CharField(max_length=50)),
                ('learner_first_name', models.CharField(max_length=50)),
                ('parent_surname', models.CharField(max_length=50)),
                ('parent_first_name', models.CharField(max_length=50)),
                ('parent_relation', models.CharField(choices=[('Mother', 'Mother'), ('Grandmother', 'Grandmother'), ('Aunt', 'Aunt'), ('Father', 'Father'), ('Grandfather', 'Grandfather'), ('Uncle', 'Uncle'), ('Sister', 'Sister'), ('Brother', 'Brother')], max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female')),
                ('id_or_passport', models.CharField(max_length=30)),
                ('citizenship', models.CharField(blank=True, null=True)),
                ('country_of_residence', models.CharField(max_length=250)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_school', models.CharField(blank=True, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.CharField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=255)),
                ('document', models.FileField(upload_to='resources')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
