# Generated by Django 5.2.3 on 2025-11-16 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_management', '0006_moment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momentvideo',
            name='moment',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-upload_date']},
        ),
        migrations.CreateModel(
            name='MomentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='moments')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=50)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='da_management.moment')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='MomentImage',
        ),
        migrations.DeleteModel(
            name='MomentVideo',
        ),
    ]
