# Generated by Django 5.2.3 on 2025-11-23 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_management', '0007_remove_momentvideo_moment_alter_announcement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerapplication',
            name='approved_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerapplication',
            name='date_rejected',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnerapplication',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='learner_applications'),
        ),
        migrations.AddField(
            model_name='learnerapplication',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learnerapplication',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learnerapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
