# Generated by Django 5.2.3 on 2025-11-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_management', '0008_learnerapplication_approved_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerapplication',
            name='date_of_birth',
            field=models.CharField(blank=True, null=True),
        ),
    ]
