# Generated by Django 5.2.3 on 2025-11-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_management', '0009_alter_learnerapplication_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerapplication',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
