# Generated by Django 5.2.3 on 2025-11-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_management', '0010_learnerapplication_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerapplication',
            name='country_of_residence',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='learnerapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='learnerapplication',
            name='id_or_passport',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='learnerapplication',
            name='learner_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='learnerapplication',
            name='learner_surname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='learnerapplication',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='learnerapplication',
            name='parent_relation',
            field=models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Grandmother', 'Grandmother'), ('Aunt', 'Aunt'), ('Father', 'Father'), ('Grandfather', 'Grandfather'), ('Uncle', 'Uncle'), ('Sister', 'Sister'), ('Brother', 'Brother')], max_length=100),
        ),
        migrations.AlterField(
            model_name='learnerapplication',
            name='parent_surname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
