# Generated by Django 5.2.3 on 2025-11-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_management', '0011_alter_learnerapplication_country_of_residence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerapplication',
            name='last_report',
            field=models.ImageField(blank=True, null=True, upload_to='learner_applications/reports'),
        ),
    ]
