# Generated by Django 5.2.3 on 2025-11-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('da_management', '0012_learnerapplication_last_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnerapplication',
            options={'ordering': ['-date_applied']},
        ),
    ]
